version: '3.8'

services:
  backend:
    build: ./backend
    command: bash -c "
      ./migrate.sh &&
      uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/saam
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - TESTING=${TESTING:-false}
      - DEBUG=true
      - SKIP_GOOGLE_AUTH=true
      - CORS_ORIGINS=http://localhost:3000
    volumes:
      - ./backend:/app
    depends_on:
      - db
      - redis

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=saam
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  postgres_data:

networks:
  default:
    name: app-network