version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/saam
      - REDIS_HOST=redis
      - GOOGLE_CREDENTIALS_PATH=/app/credentials/saam-bus-2143aa7b9c18.json
      - CORS_ORIGINS=http://localhost:3000
    volumes:
      - ../backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    command: bash -c "sleep 5 && /app/scripts/db-migrate.sh && uvicorn app.main:app --host 0.0.0.0 --port 8000"

  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    depends_on:
      - backend

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=saam
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:6
    ports:
      - "6379:6379"

volumes:
  postgres_data: